version: "3.0"
services:
  callApp:
    image: call-app
    build: 
      context: ./CallApp
    volumes:
      - ./CallApp/:/app
    networks:
      - demo_net
  data-generation:
    image: data-generation
    build: 
      context: .
      dockerfile: ./DataGenerationNewDemoPython/Dockerfile
      args: 
        REVDEBUG_PYTHON_VERSION: 3.9
    ports:
      - 7000:7000
    environment:
        REVDEBUG_HOST: ${REVDEBUG_HOST:-}
        REVDEBUG_FORCE_TLS:  ${REVDEBUG_FORCE_TLS:-true}
    volumes:
      - .:/app
    networks:
      - demo_net
  selenium-standalone-chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 7900:7900
      - 81:80
    networks:
      - demo_net
  web:
    build: 
      context: selenium_app/
    image: selenium-app
    ports: 
      - 8080:8080
    command: uvicorn --host=0.0.0.0 --port=8080 main:app
    networks:
      - demo_net


networks:
    demo_net:
        driver: bridge
        ipam:
            driver: default
            config:   
                - subnet: 192.168.2.0/24